allow to use the role without partitioning
AerisCloud/ansible-disk pull request #24
Opened 2021-12-03 15:11 UTC by mjourdan

Because we don't need partitioning on our additional disks, we made some changes to the role.

We added a new variable `disk_enable_partitioning` set to true by default, so that the behaviour of the role will be the same as before when an item in the list has no `part` defined (ie, a partition will be created anyway).

2021-12-03 23:53 UTC, christopherobin requested changes
I never used `ternary` before so the syntax is throwing me a bit off :D otherwise it looks good.
Just need to fix the typo and that old line and I'll merge this for you

2021-12-03 23:53 UTC, christopherobin commented on README.md
> +* `disk_enable_partioning: false` to optionnaly disable partitioning
You can drop `optionally` and just say `to disable partitioning` (or update the typo `optionnaly -> optionally`)

2021-12-03 23:53 UTC, christopherobin commented on tasks/main.yml
> +    #dev: '{{ item.part | default(item.disk + "1") }}'
You can remove this line

2021-12-07 08:09 UTC, mjourdan commented
> I never used `ternary` before so the syntax is throwing me a bit off :D

An alternative to get rid of that would be to change the role so that part would need to be explicitly requested to be created. The overall logic would be simpler but I figured perhaps it was best to go the ternary way for retro-compatibility sake.

> otherwise it looks good. Just need to fix the typo and that old line and I'll merge this for you

Yeah, sorry for that. Done.

Thanks for your fast feedback!

2021-12-07 23:20 UTC, MiLk approved these changes

2022-01-12 23:21 UTC, merged